name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.1.3'

    steps:
    - name: release please
      uses: google-github-actions/release-please-action@v4
      id: release
      with:
        release-type: ruby
