name: Ruby

on:
  push:
    branches:
      - main

permissions:
  checks: write
  statuses: write
  contents: write
  packages: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: release please
      uses: google-github-actions/release-please-action@v4
      id: release
      with:
        release-type: ruby
